/**
 * OpenRouter API service for image generation
 * Uses OpenRouter's chat completions endpoint with image generation modalities
 */

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = 'google/gemini-2.5-flash-image-preview'; // Model identifier on OpenRouter

/**
 * Generates a spooky version of the uploaded image based on the selected style.
 * Uses OpenRouter API with image generation capabilities.
 */
export const generateSpookyImage = async (
  base64Image: string,
  stylePrompt: string
): Promise<string> => {
  try {
    const apiKey = process.env.API_KEY;
    
    if (!apiKey) {
      throw new Error("API key is not configured. Please set your OpenRouter API key.");
    }

    // Construct the transformation prompt
    const prompt = `Transform the person in this image into a Halloween character based on the style: "${stylePrompt}".
            
CRITICAL GUIDELINES:
1. EYE COLOR IS SACROSANCT: The person's original eye color MUST NOT be changed under any circumstances. If a style demands glowing eyes, you may add a subtle glow effect OVER the existing eyes, but the original color must remain visible beneath. This is the most important rule.
2. PRESERVE CORE FACIAL IDENTITY: The person's fundamental facial structure (jawline, nose shape, chin, etc.) MUST be preserved. The person in the output image must be clearly and instantly recognizable as the person from the input image.
3. ALLOW CREATIVE SFX & ACCESSORIES: While preserving identity, you are encouraged to add creative, non-destructive transformations. This includes:
    - Thematic accessories like hats, glasses, crowns, or horns.
    - Thematic SFX makeup such as stitches, scales, cracks, veins, or monster-like skin textures.
    - These additions should be applied like high-quality movie prosthetics and makeup, not by changing the underlying face.
4. TRANSFORM THE CLOTHING: Completely change the person's clothes into a full, photorealistic costume that matches the style prompt. This is a complete redesign of the clothing.
5. PRESERVE THE BACKGROUND: The original background of the photo MUST remain exactly the same. IGNORE any instructions in the style prompt about changing the background.
6. MAINTAIN PHOTOREALISM: The final image must look like a real, high-quality photograph.

Return ONLY the edited image. Do not add any text.`;

    // Make the API request to OpenRouter
    const response = await fetch(OPENROUTER_API_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: MODEL,
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'image_url',
                image_url: {
                  url: base64Image, // OpenRouter accepts data URLs directly
                },
              },
              {
                type: 'text',
                text: prompt,
              },
            ],
          },
        ],
        modalities: ['image', 'text'],
        image_config: {
          aspect_ratio: '1:1', // 1024x1024 for consistent output
        },
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('OpenRouter API Error:', errorData);
      
      if (response.status === 401) {
        throw new Error("Invalid API key. Please check your OpenRouter API key.");
      } else if (response.status === 429) {
        throw new Error("Rate limit exceeded. Please try again in a moment.");
      } else {
        throw new Error(`API request failed: ${errorData.error?.message || response.statusText}`);
      }
    }

    const result = await response.json();

    // Extract the generated image from the response
    if (result.choices && result.choices.length > 0) {
      const message = result.choices[0].message;
      
      // Check for images in the response
      if (message.images && message.images.length > 0) {
        const imageUrl = message.images[0].image_url.url;
        return imageUrl; // Returns base64 data URL
      }
      
      // If no image but there's text content, it might explain why
      if (message.content) {
        console.warn("AI returned text instead of image:", message.content);
        throw new Error("The AI could not process this specific image. Please try another photo.");
      }
    }

    throw new Error("No image generated by the AI.");

  } catch (error) {
    console.error("OpenRouter API Error:", error);
    
    // Re-throw with user-friendly message
    if (error instanceof Error) {
      throw error;
    }
    
    throw new Error("Failed to generate image. Please try again.");
  }
};